import { USER_ROLES } from "./roles";

// src/constants/permissions.js
export const PERMISSIONS = {
  // Business Management (Super Admin only)
  MANAGE_BUSINESSES: 'manage_businesses',
  
  // User Management
  CREATE_USERS: 'create_users',
  EDIT_USERS: 'edit_users',
  DELETE_USERS: 'delete_users',
  ASSIGN_ROLES: 'assign_roles',
  
  // Product Management
  CREATE_PRODUCTS: 'create_products',
  EDIT_PRODUCTS: 'edit_products',
  DELETE_PRODUCTS: 'delete_products',
  APPROVE_PRODUCTS: 'approve_products',
  VIEW_PRODUCTS: 'view_products',
  VIEW_ALL_PRODUCTS: 'view_all_products', // including drafts/pending
  
  // Public Access
  VIEW_APPROVED_PRODUCTS: 'view_approved_products'
};

export const ROLE_PERMISSIONS = {
  [USER_ROLES.SUPER_ADMIN]: [
    PERMISSIONS.MANAGE_BUSINESSES,
    PERMISSIONS.CREATE_USERS,
    PERMISSIONS.EDIT_USERS,
    PERMISSIONS.DELETE_USERS,
    PERMISSIONS.ASSIGN_ROLES,
    PERMISSIONS.CREATE_PRODUCTS,
    PERMISSIONS.EDIT_PRODUCTS,
    PERMISSIONS.DELETE_PRODUCTS,
    PERMISSIONS.APPROVE_PRODUCTS,
    PERMISSIONS.VIEW_ALL_PRODUCTS
  ],
  [USER_ROLES.BUSINESS_ADMIN]: [
    PERMISSIONS.CREATE_USERS,
    PERMISSIONS.EDIT_USERS,
    PERMISSIONS.DELETE_USERS,
    PERMISSIONS.ASSIGN_ROLES,
    PERMISSIONS.CREATE_PRODUCTS,
    PERMISSIONS.EDIT_PRODUCTS,
    PERMISSIONS.DELETE_PRODUCTS,
    PERMISSIONS.APPROVE_PRODUCTS,
    PERMISSIONS.VIEW_ALL_PRODUCTS
  ],
  [USER_ROLES.EDITOR]: [
    PERMISSIONS.CREATE_PRODUCTS,
    PERMISSIONS.EDIT_PRODUCTS,
    PERMISSIONS.VIEW_ALL_PRODUCTS
  ],
  [USER_ROLES.APPROVER]: [
    PERMISSIONS.APPROVE_PRODUCTS,
    PERMISSIONS.VIEW_ALL_PRODUCTS
  ],
  [USER_ROLES.VIEWER]: [
    PERMISSIONS.VIEW_PRODUCTS
  ]
};